service: reko-lambda

provider:
  name: aws
  runtime: python3.7
  region: us-east-2
  profile: ${file(../config.${self:provider.stage}.json):reko-lambda.profile}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - Fn::Join:
          - ''
          - - ${self:custom.videosBucketArn}
            - '/*'
custom:
  videosBucketArn:
    Fn::Join:
      - ':'
      - - arn
        - aws
        - s3
        - ''
        - ''
        - ${file(../config.${self:provider.stage}.json):reko-lambda.videos_bucket}

functions:
  startProcessingVideo:
    handler: handler.start_processing_video
    events:
      - s3:
          bucket: ${file(../config.${self:provider.stage}.json):reko-lambda.videos_bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4